version: '3'

services:
  backend:
    container_name: rest-api
    build:
      context: ./backend
      dockerfile: django.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  frontend:
    container_name: rest-app
    build:
      context: ./frontend
      dockerfile: react.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/app
    command: "npm start"